/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2022-02-16 10:13:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.hspt;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_002dmy_002dsckbdreq_002ddetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:substring", org.apache.taglibs.standard.functions.Functions.class, "substring", new Class[] {java.lang.String.class, int.class, int.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/A_TeachingMaterial/7.LastProject/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/covid_compass/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1639443128000L));
    _jspx_dependants.put("jar:file:/D:/A_TeachingMaterial/7.LastProject/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/covid_compass/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/A_TeachingMaterial/7.LastProject/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/covid_compass/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<head>\r\n");
      out.write("<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=553e55e7a953a05a2adfe2bfc2932452&libraries=services\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<title>병상신청 정보조회</title>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function prettifyDateFn(timeValue){\r\n");
      out.write("  if(timeValue){\r\n");
      out.write("    var dateObj = new Date(timeValue);\r\n");
      out.write("    var year = dateObj.getFullYear();\r\n");
      out.write("    var month = dateObj.getMonth() + 1;\r\n");
      out.write("    month += '';\r\n");
      out.write("    if(month.length < 2){\r\n");
      out.write("      month = '0' + month;\r\n");
      out.write("    }\r\n");
      out.write("    var date = dateObj.getDate();\r\n");
      out.write("    date += '';\r\n");
      out.write("    if(date.length < 2){\r\n");
      out.write("      date = '0' + date;\r\n");
      out.write("    }\r\n");
      out.write("    return year + \"-\" + month + \"-\" + date;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("function prettifyDetailDate(timeValue){\r\n");
      out.write("\tif(timeValue){\r\n");
      out.write("\t\tvar dateObj = new Date(timeValue);\r\n");
      out.write("\t\tvar year = dateObj.getFullYear();\r\n");
      out.write("\t\tvar month = dateObj.getMonth() + 1;\r\n");
      out.write("\t\tvar date = dateObj.getDate();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar hour = dateObj.getHours();\r\n");
      out.write("\t\tvar minute = dateObj.getMinutes();\r\n");
      out.write("\t\tvar second = dateObj.getSeconds();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdate += '';\r\n");
      out.write("\t\tif(date.length < 2){\r\n");
      out.write("\t\t\tdate = '0' + date;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tmonth += '';\r\n");
      out.write("\t\tif(month.length < 2){\r\n");
      out.write("\t\t\tmonth = '0' + month;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\thour += '';\r\n");
      out.write("\t\tif(hour.length < 2){\r\n");
      out.write("\t\t\thour = '0' + hour;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tminute += '';\r\n");
      out.write("\t\tif(minute.length < 2){\r\n");
      out.write("\t\t\tminute = '0' + minute;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tsecond += '';\r\n");
      out.write("\t\tif(second.length < 2){\r\n");
      out.write("\t\t\tsecond = '0' + second;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn year + \"-\" + month + \"-\" + date + \" \" + hour + \":\" + minute + \":\" + second;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function cancle_go(sckbdreqNo, childNo, type){\r\n");
      out.write("\t\r\n");
      out.write("\tif(!confirm('병상신청을 취소하시겠습니까?')) return; \r\n");
      out.write("\t\r\n");
      out.write("\tvar url = '");
      out.print(request.getContextPath());
      out.write("/rest-hspt/process-sckbdreq-cancle';\r\n");
      out.write("\t\r\n");
      out.write("\tvar data =\r\n");
      out.write("\t\t{\r\n");
      out.write("    \t\t 'sckbdreqNo' : sckbdreqNo\r\n");
      out.write("    \t\t,'childNo' : childNo\r\n");
      out.write("    \t\t,'type' : type\r\n");
      out.write("    \t}\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : url,\r\n");
      out.write("\t\ttype : 'post',\r\n");
      out.write("\t\tdataType : 'json',\r\n");
      out.write("\t\tdata : data,\r\n");
      out.write("\t\tsuccess : function(dataMap) {\r\n");
      out.write("\t\t\talert('병상신청을 취소하였습니다.');\r\n");
      out.write("\t\t\tCloseWindow();\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror : function(error) {\r\n");
      out.write("\t\t\talert('error' + error.status);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})\t\t\r\n");
      out.write("}\r\n");
      out.write("window.onload = function(){\r\n");
      out.write("  \r\n");
      out.write("  if('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resYmd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'){\r\n");
      out.write("    var resYmd = new Date('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resYmd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("').getTime();\r\n");
      out.write("      $('#resYmd').html(prettifyDateFn(resYmd));\r\n");
      out.write("  }\r\n");
      out.write("  if('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdReqYmd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'){\r\n");
      out.write("    var sckbdReqYmd = new Date('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdReqYmd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("').getTime();\r\n");
      out.write("      $('#sckbdReqYmd').html(prettifyDetailDate(sckbdReqYmd));\r\n");
      out.write("  }\r\n");
      out.write("\t\r\n");
      out.write("  var test = false;\r\n");
      out.write("  var cancleYmd = new Date('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cancleYmd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("').getTime();\r\n");
      out.write("\r\n");
      out.write("  test = parseInt(Date.now()) < parseInt(cancleYmd);\r\n");
      out.write("\t\r\n");
      out.write("  console.log(parseInt(Date.now()), parseInt(cancleYmd));\r\n");
      out.write("  console.log(test);\r\n");
      out.write("  \r\n");
      out.write("  console.log('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.lastRecord}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' == true);\r\n");
      out.write("  console.log('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.lastRecord}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' == 'true');\r\n");
      out.write("\r\n");
      out.write("  // 가장 최신의 레코드인지 확인하라.\r\n");
      out.write("  if('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.lastRecord}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' == 'true'){\r\n");
      out.write("\t  // 승인대기상태이면 취소가능한지 판단하라.\r\n");
      out.write("\t  if('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.sckbdreqCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' == '승인대기'){\r\n");
      out.write("\t\t  if(test){\r\n");
      out.write("\t\t\t  $('#cancleBtn').attr('disabled', false);\r\n");
      out.write("\t\t  }else{\r\n");
      out.write("\t\t\t  $('#cancleBtn').attr('disabled', true);\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t  \treturn;\r\n");
      out.write("\t  }\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  // 가장 최신의 레코드가 아니면 취소버튼 비활성화\r\n");
      out.write("  \r\n");
      out.write("  // 승인대기상태가 아니면 취소버튼 비활성화\r\n");
      out.write("  $('#cancleBtn').attr('disabled', true);\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<section class=\"content\">\r\n");
      out.write("          <div class=\"card\" style=\"margin: 1px; height: 763px; margin-top: 13px;\">\r\n");
      out.write("            <div class=\"card-body pb-0\" style=\"padding-top: 8px;\">\r\n");
      out.write("              <table class=\"table table-bordered\" style=\"border-left-color: white; border-right-color: white;\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <th colspan=\"4\" style=\"font-size: 17px; padding: 7px;\">\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"row m-0\" style=\"justify-content: space-between;\">\r\n");
      out.write("                    \t\t<label style=\"font-size: 17px; margin: 0px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.type eq 'A' ? '이원' : '입소'}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("신청 환자상세</label>\r\n");
      out.write("                    \t\t<button type=\"button\" class=\"btn btn-sm btn-primary\" id=\"enableReadRrn\" onclick=\"enableOpenRrn(this);\" data-enable=\"N\" data-rrn=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.rrn }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" data-manageNo=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.manageNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">개인정보 열람</button>\r\n");
      out.write("                    \t</div>                    \r\n");
      out.write("\t\t\t\t\t\t<div id=\"hiddenRrn\" style=\"display: none;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.rrn }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                    \r\n");
      out.write("                    </th>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody id=\"req-inptnt-detail-info-module\">\r\n");
      out.write("                  <tr class=\"ddoing req-inptnt-detail-info\" style=\"height: 15px;\"></tr>\r\n");
      out.write("                  <tr class=\"shittr req-inptnt-detail-info\">\r\n");
      out.write("                    <th class=\"col-sm-3\">성명</th>\r\n");
      out.write("                    <td class=\"col-sm-4\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.pstiNm }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                    <th class=\"col-sm-2\">국적</th>\r\n");
      out.write("                    <td class=\"col-sm-3\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.nlty }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr class=\"shittr req-inptnt-detail-info\">\r\n");
      out.write("                    <th>병상신청일자</th>\r\n");
      out.write("                    <td id=\"sckbdReqYmd\"></td>\r\n");
      out.write("                    <th>백신접종</th>\r\n");
      out.write("                    <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.vacType }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr class=\"shittr req-inptnt-detail-info\">\r\n");
      out.write("                    <th>성별</th>\r\n");
      out.write("                    <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.gender }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                    <th>나이</th>\r\n");
      out.write("                    <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.age }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr class=\"shittr req-inptnt-detail-info\">\r\n");
      out.write("                    <th>확정일자</th>\r\n");
      out.write("                    <td id=\"resYmd\"></td>\r\n");
      out.write("                    <th>결과</th>\r\n");
      out.write("                    <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.pstvYn }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr class=\"shittr req-inptnt-detail-info\">\r\n");
      out.write("                    <th>발열여부</th>\r\n");
      out.write("                    <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.feverYn }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                    <th>임신여부</th>\r\n");
      out.write("                    <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.pregnYn }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr class=\"shittr req-inptnt-detail-info\">\r\n");
      out.write("                    <th style=\"vertical-align: middle; padding: 0px;padding-left: 9px;font-size: 12px;\">주민/외국인<br>등록번호</th>\r\n");
      out.write("                    <td id=\"openRrn\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:substring(sckbdreqDetailCommand.rrn,0,8) }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("******</td>\r\n");
      out.write("                    <th>연락처</th>\r\n");
      out.write("                    <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.pstiTelno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr class=\"shittr req-inptnt-detail-info\">\r\n");
      out.write("                    <th>주소</th>\r\n");
      out.write("                    <td colspan=\"3\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.pstiAdres }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr class=\"shittr req-inptnt-detail-info\">\r\n");
      out.write("                    <th>증상</th>\r\n");
      out.write("                    <td colspan=\"3\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.symptms }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr class=\"shittr req-inptnt-detail-info\">\r\n");
      out.write("                    <th>병상신청기관</th>\r\n");
      out.write("                    <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.instNm }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.ltctNm }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                    <th>기관연락처</th>\r\n");
      out.write("                    <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.instTelno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.ltctTelno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr class=\"shittr req-inptnt-detail-info\">\r\n");
      out.write("                    <th>신청기관 주소</th>\r\n");
      out.write("                    <td colspan=\"3\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.instAdres }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.ltctAdres }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr class=\"shittr\">\r\n");
      out.write("                    <th>신청결과</th>\r\n");
      out.write("                    <td colspan=\"3\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.sckbdreqCode }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                  </tr>                  \r\n");
      out.write("                </tbody>\r\n");
      out.write("              </table>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body pb-0\" style=\"\">\r\n");
      out.write("              <table class=\"table table-bordered\">\r\n");
      out.write("                <tbody>\r\n");
      out.write("                  <tr class=\"shittr\">\r\n");
      out.write("                    <th class=\"col-md-3\">진료병원</th>\r\n");
      out.write("                    <td class=\"col-md-4\" id=\"dgnssHsptNm\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.dgnssHsptNm }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                    <th class=\"col-md-2\">진료결과</th>\r\n");
      out.write("                    <td class=\"col-md-3\" id=\"dgnssResultCode\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.dgnssResultCode }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr class=\"shittr\">\r\n");
      out.write("                    <th rowspan=\"4\" style=\"vertical-align: middle;\">진료메모</th>\r\n");
      out.write("                    <td colspan=\"3\" style=\"height: 111px; vertical-align: middle; text-align: left;\" id=\"dgnssNote\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.dgnssNote }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("              </table>\r\n");
      out.write("                  <div class=\"form-group row\" style=\"padding-top: 6px;\">\r\n");
      out.write("                    <div class=\"col-md-6\"></div>\r\n");
      out.write("                    <div class=\"col-md-3\">\r\n");
      out.write("                      <button type=\"button\" id=\"cancleBtn\" class=\"btn btn-block btn-primary btn-sm\" style=\"background-color: #1a4f72; border-color: #1a4f72;\"\r\n");
      out.write("                              onclick=\"cancle_go('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.sckbdreqNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.childNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.type }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdreqDetailCommand.type eq 'A' ? '이원' : '입소'}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("신청취소</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3\">\r\n");
      out.write("                      <button type=\"button\" class=\"btn btn-block btn-danger btn-sm\" onclick=\"window.close();\">닫기</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
