/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2022-02-17 06:59:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.ltct;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sckbdcnt_002dmodify_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1639443128000L));
    _jspx_dependants.put("jar:file:/D:/A_TeachingMaterial/7.LastProject/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/covid_compass/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/A_TeachingMaterial/7.LastProject/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/covid_compass/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<head></head>\r\n");
      out.write("\r\n");
      out.write("<title>병상등록</title>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<script>\r\n");
      out.write("function Close(){\r\n");
      out.write("\tvar check = confirm(\"페이지를 닫으시겠습니까?\");\r\n");
      out.write("\tif(check){\r\n");
      out.write("\t\twindow.close();\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function submitbutton(){\r\n");
      out.write("\tvar sckbdCnt = $('#sckbdCnt').val(); // 입력 병상\r\n");
      out.write("\tvar rmndCnt = $('#rmndCnt').val(); // 잔여병상\r\n");
      out.write("\tif(sckbdCnt == \"\" || sckbdCnt == \"0\"){\r\n");
      out.write("\t\talert(\"등록할 병상을 입력해주세요.\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar parseCnt = parseInt(sckbdCnt);\r\n");
      out.write("\tif(parseCnt<0){\r\n");
      out.write("\t\tvar minCnt = parseCnt * -1;\r\n");
      out.write("\t\tif(minCnt > rmndCnt){\r\n");
      out.write("\t\t\talert(\"잔여병상 수를 초과하였습니다.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : '");
      out.print(request.getContextPath());
      out.write("/rest-ltct/sckbd-cnt-modify',\r\n");
      out.write("\t\tdata : {\"sckbdCnt\" : sckbdCnt},\r\n");
      out.write("\t\ttype: 'post',\r\n");
      out.write("\t\tsuccess : function(res){\r\n");
      out.write("\t\t\talert(\"병상이 성공적으로 등록되었습니다.\");\r\n");
      out.write("\t\t\twindow.opener.location.reload();\r\n");
      out.write("\t\t\tlocation.reload();\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror : function(error){\r\n");
      out.write("\t\t\talert('error' + error.status);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\t<div class=\"card card-success\">\r\n");
      out.write("\t\t<div class=\"register-card-body\"> \r\n");
      out.write("\t\t<div class=\"card-header\" style=\"background-color: #1a4f72; color:white;\">\r\n");
      out.write("\t\t\t<h3 class=\"card-title\">병상 등록</h3>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"card-body \">\r\n");
      out.write("\t\t\t  <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-1\"></div>\r\n");
      out.write("          <div class=\"col-md-6\">\r\n");
      out.write("            <i class=\"fas fa-procedures fa-3x\" style=\"color: #1a4f72;\"></i> <span style=\"font-size: 36px; color: #6c757d;\">&nbsp;&nbsp;");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdCountAndStats.rmndSckbdCnt }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("석</span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"input-group col-md-4 pr-0 pl-0\" style=\"margin-top: 10px;\">\r\n");
      out.write("            <input class=\"form-control\" type=\"number\" name=\"sckbdCnt\" id=\"sckbdCnt\" placeholder=\"\" /> <span class=\"input-group-append col-sm-4 pl-0\">\r\n");
      out.write("              <button type=\"button\" class=\"btn btn-block btn-primary btn-sm\" style=\"background: #1a4f72; color: #ffffff; border-color: #1a4f72; height: 31px;\" onclick=\"submitbutton();\">등록</button>\r\n");
      out.write("            </span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-1\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"card-header\" style=\"background-color: #1a4f72; color:white;\">\r\n");
      out.write("\t\t\t<h3 class=\"card-title\">사용현황</h3>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"card-body pl-0 pr-0\">\r\n");
      out.write("\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("                <table class=\"table table-bordered\">\r\n");
      out.write("                  <thead>\r\n");
      out.write("                  \t<tr>\r\n");
      out.write("                  \t\t<th colspan=\"5\" style=\"text-align:center;\">현황</th>\r\n");
      out.write("                  \t</tr>\r\n");
      out.write("                  </thead>\r\n");
      out.write("                  <tbody>\r\n");
      out.write("                    <tr style=\"text-align: center; font-weight: bold; background-color:#f5fafc \">\r\n");
      out.write("                      <th class=\"col-md-2\">총 병상</th>\r\n");
      out.write("                      <th class=\"col-md-2\">입소환자</th>\r\n");
      out.write("                      <th class=\"col-md-2\">잔여병상</th>\r\n");
      out.write("                      <th class=\"col-md-2\">승인대기</th>\r\n");
      out.write("                      <th class=\"col-md-2\">가동률</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr style=\"text-align: center\">\r\n");
      out.write("                      <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdCountAndStats.sckbdCnt }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                      <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdCountAndStats.isoptntCount }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                      <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdCountAndStats.rmndSckbdCnt }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                      <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdCountAndStats.sckbdreqCount }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                      <td><span class=\"badge badge-success\" style=\"background-color:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdCountAndStats.color}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("; border-color: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdCountAndStats.color}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(';');
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdCountAndStats.opRate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("%</span></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                  </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("                <table class=\"table table-bordered\">\r\n");
      out.write("                  <thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th colspan=\"4\" style=\"text-align:center;\">전날 현황</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("                  </thead>\r\n");
      out.write("                  <tbody>\r\n");
      out.write("                    <tr style=\"text-align: center; font-weight: bold; background-color:#f5fafc \">\r\n");
      out.write("                      <th class=\"col-md-3\">진료요청</th>\r\n");
      out.write("                      <th class=\"col-md-3\">격리인원</th>\r\n");
      out.write("                      <th class=\"col-md-3\">이원인원</th>\r\n");
      out.write("                      <th class=\"col-md-3\">퇴원인원</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr style=\"text-align: center\">\r\n");
      out.write("                      <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdCountAndStats.reqDgnssCnt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                      <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdCountAndStats.inIsoptntCnt }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                      <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdCountAndStats.outIsoptntCnt }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                      <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdCountAndStats.rlsedCnt }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                  </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-md-3 float-right\">\r\n");
      out.write("\t\t\t<button type=\"button\" onclick=\"Close();\" class=\"btn btn-block btn-danger \">닫기</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<input type=\"hidden\" id=\"rmndCnt\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sckbdCountAndStats.rmndSckbdCnt }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/ltct/sckbdcnt-modify.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("sckbdCountAndStats");
      // /WEB-INF/views/ltct/sckbdcnt-modify.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/ltct/sckbdcnt-modify.jsp(5,0) '${sckbdCountAndStats }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sckbdCountAndStats }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
