



CREATE OR REPLACE PROCEDURE PROC_EMP01(
       P_EID IN EMPLOYEES.EMPLOYEE_ID%TYPE,
       P_DNAME OUT DEPARTMENTS.DEPARTMENT_NAME%TYPE,
       P_CNT OUT NUMBER,
       P_SAL OUT NUMBER)   
     IS 
     BEGIN
       SELECT B.DEPARTMENT_NAME,COUNT(*),ROUND(AVG(SALARY))
         INTO P_DNAME,P_CNT,P_SAL
         FROM (SELECT DEPARTMENT_ID AS DID 
                FROM EMPLOYEES 
                WHERE EMPLOYEE_ID=P_EID)A,DEPARTMENTS B,EMPLOYEES C
          WHERE A.DID=B.DEPARTMENT_ID
            AND C.DEPARTMENT_ID=A.DID
       GROUP BY B.DEPARTMENT_NAME;  
      END;
  
  (실행)
  
   DECLARE
       V_DNAME DEPARTMENTS.DEPARTMENT_NAME%TYPE;
       V_CNT  NUMBER:=0;
       V_SAL  NUMBER:=0;
    BEGIN
       PROC_EMP01(109,V_DNAME,V_CNT,V_SAL); --EXCUTE는 독립실행할때 사용하는 거고 블록 안에서는 생략해야 한다.
       DBMS_OUTPUT.PUT_LINE('부서명: '||V_DNAME); 
       DBMS_OUTPUT.PUT_LINE('직원수: '||V_CNT);
       DBMS_OUTPUT.PUT_LINE('평균급여: '||V_SAL);
       
    END;   