SELECT A.EMPLOYEE_ID AS 사원번호,
       A.EMP_NAME AS 사원명,
       A.DEPARTMENT_ID AS 부서번호,
       DAV.DNM AS 부서명,
       A.SALARY AS 급여,
       DAV.DAS AS 부서평균급여
 FROM(SELECT B.DEPARTMENT_ID AS DID,
             B.DEPARTMENT_NAME AS DNM, 
             ROUND(AVG(A.SALARY)) AS DAS
             FROM HR.EMPLOYEES A,HR.DEPARTMENTS B
             WHERE A.DEPARTMENT_ID=B.DEPARTMENT_ID
             GROUP BY B.DEPARTMENT_ID,B.DEPARTMENT_NAME) DAV,   
     HR.EMPLOYEES A
    WHERE A.DEPARTMENT_ID=DAV.DID
      AND A.SALARY<DAV.DAS
    ORDER BY 3;
