/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2022-02-22 05:22:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.pbhlth;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class smple_002dlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&amp;display=fallback\">\r\n");
      out.write(" <!-- Font Awesome -->\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"../resources/bootstrap/plugins/fontawesome-free/css/all.min.css\">\r\n");
      out.write(" <!-- Theme style -->\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"../resources/bootstrap/dist/css/adminlte.min.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"../resources/bootstrap/plugins/jquery/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<title></title>\r\n");
      out.write("<body>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.7.7/handlebars.min.js\"></script>\r\n");
      out.write("<script type=\"text/x-handlebars-template\"  id=\"smpl-list-template\" >\r\n");
      out.write("{{#each .}}\r\n");
      out.write("          <tr style=\"cursor: pointer;\"\r\n");
      out.write("\t\t\tdata-inst-no=\"{{instNo}}\" data-manage-no=\"{{manageNo}}\" data-smpl-no=\"{{smplNo}}\"\r\n");
      out.write("            onclick=\"showDetail('{{smplNo}}', '{{manageNo}}')\"\r\n");
      out.write("            class=\"each-smpl-element\">\r\n");
      out.write("            <td>\r\n");
      out.write("\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t  <div class=\"form-check\">\r\n");
      out.write("\t\t\t\t\t  <input type=\"checkbox\" class=\"form-check-input\" value=\"{{smplNo}}\" data-manage-no=\"{{manageNo}}\"\r\n");
      out.write("\t\t\t\t\t\t  name=\"psti_req_check\" onclick=\"cancleAll(this);\">\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t </td>\r\n");
      out.write("            <td class=\"smplNo\" nno=\"{{smplNo}}\">{{smplNo}}</td>\r\n");
      out.write("            <td style=\"text-align: left;\">{{instNm}}</td>\r\n");
      out.write("            <td>{{prettifyDate reqYmd}}</td>\r\n");
      out.write("            <td>{{chkdYn}}</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("{{/each}}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/x-handlebars-template\"  id=\"inptnt-pagination-template\" >\r\n");
      out.write("    <li class=\"page-item each-inptnt-pagination-element\"><a class=\"page-link\" href=\"1\"> <i class=\"fas fa-angle-double-left\" style=\"color:#1a4f72;\"></i>\r\n");
      out.write("    </a></li>\r\n");
      out.write("    <li class=\"page-item each-inptnt-pagination-element\"><a class=\"page-link\" href=\"{{#if prev}}{{prevPageNum}}{{/if}}\"> <i class=\"fas fa-angle-left\" style=\"color:#1a4f72;\"></i>\r\n");
      out.write("    </a></li>\r\n");
      out.write("\r\n");
      out.write("{{#each pageNum}}\r\n");
      out.write("    <li class=\"page-item each-inptnt-pagination-element {{signActive this}}\" ><a class=\"page-link\" href=\"{{this}}\" >{{this}}</a></li>\r\n");
      out.write("{{/each}}\r\n");
      out.write("\r\n");
      out.write("    <li class=\"page-item each-inptnt-pagination-element\"><a class=\"page-link\" href=\"{{#if next}}{{nextPageNum}}{{/if}}\"> <i class=\"fas fa-angle-right\" style=\"color:#1a4f72;\"></i>\r\n");
      out.write("    </a></li>\r\n");
      out.write("    <li class=\"page-item each-inptnt-pagination-element\"><a class=\"page-link\" href=\"{{realEndPage}}\"> <i class=\"fas fa-angle-double-right\" style=\"color:#1a4f72;\"></i>\r\n");
      out.write("</a></li>\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("Handlebars.registerHelper({\r\n");
      out.write("\"prettifyDate\" : function(timeValue){\r\n");
      out.write("\tif(timeValue){\r\n");
      out.write("\t\tvar dateObj = new Date(timeValue);\r\n");
      out.write("\t\tvar year = dateObj.getFullYear();\r\n");
      out.write("\t\tvar month = dateObj.getMonth() + 1;\r\n");
      out.write("\t\tmonth += '';\r\n");
      out.write("\t\tif(month.length < 2){\r\n");
      out.write("\t\t\tmonth = '0' + month;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar date = dateObj.getDate();\r\n");
      out.write("\t\tdate += '';\r\n");
      out.write("\t\tif(date.length < 2){\r\n");
      out.write("\t\t\tdate = '0' + date;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn year + \"-\" + month + \"-\" + date;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn \"없음\";\r\n");
      out.write("},\r\n");
      out.write("\"signActive\" : function(pageNum){\r\n");
      out.write("  if(pageNum == page) return 'active';\r\n");
      out.write("}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("var page = 1;\r\n");
      out.write("\r\n");
      out.write("window.onload = function(){\r\n");
      out.write(" \t//generateQR();\r\n");
      out.write(" \t\r\n");
      out.write("  var url = '");
      out.print(request.getContextPath() );
      out.write("/rest-pbht/smpl-list';\r\n");
      out.write("  \r\n");
      out.write("  list_go(url,page );\r\n");
      out.write("\t$('ul.pagination').on('click','li a',function(event){\r\n");
      out.write("\t\tif($(this).attr(\"href\")) {\r\n");
      out.write("\t\t\tpage=$(this).attr(\"href\");\r\n");
      out.write("\t\t\tgetPage(url, make_form(page));\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("function make_form(pageParam, search){\r\n");
      out.write("  var jobForm=$('#jobForm');\r\n");
      out.write("  \r\n");
      out.write("  if(!pageParam) page = 1;\r\n");
      out.write("  \r\n");
      out.write("  page = pageParam;\r\n");
      out.write("  \r\n");
      out.write("  jobForm.find(\"[name='page']\").val(page);\r\n");
      out.write("  jobForm.find(\"[name='perPageNum']\").val($('select[name=\"perPageNum\"]').val());\r\n");
      out.write("//  jobForm.find(\"[name='perPageNum']\").val(2);\r\n");
      out.write("  if(search){\r\n");
      out.write("\t  jobForm.find(\"[name='searchType']\").val($('select[name=\"searchType\"]').val());\r\n");
      out.write("\t  jobForm.find(\"[name='keyword']\").val($('#keywordId').val());\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  return jobForm;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function list_go(url, pageParam, search){\r\n");
      out.write("\t\r\n");
      out.write("  getPage(url, make_form(pageParam, search));\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getPage(handelbarsProcessingURL, form){\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("    url : handelbarsProcessingURL,\r\n");
      out.write("    type : 'get',\r\n");
      out.write("    dataType : 'json',\r\n");
      out.write("    data : form.serialize(),\r\n");
      out.write("    success : function(dataMap){\r\n");
      out.write("    \t$('#smpl-list-table-tbody').html(\"\");\r\n");
      out.write("    \t\r\n");
      out.write("     \tif(dataMap.smplList.length == 0){\r\n");
      out.write("     \t\t\r\n");
      out.write("     \t\t$('#smpl-list-table-tbody').html('<tr class=\"each-smpl-element\" ><td colspan=\"5\" id=\"noSemlpeData\">데이터 로딩중 입니다.</td></tr>');\r\n");
      out.write("    \t\t$('#noSemlpeData').html('데이터가 없습니다.');\r\n");
      out.write("    \t\t$('#option_b1').attr(\"disabled\", true);\r\n");
      out.write(" \t      \t$('#option_b2').attr(\"disabled\", true);\r\n");
      out.write(" \t      \tsearchfalse();\r\n");
      out.write("    \t\tdataMap.pageMaker.endPage = 1;\r\n");
      out.write("      \t\tprintPagination(dataMap.pageMaker, $('#inptnt-list-pagination-ul'), $('#inptnt-pagination-template'), '.each-inptnt-pagination-element');\r\n");
      out.write("    \t}else{\r\n");
      out.write("    \t\t$('#option_b1').attr(\"disabled\", false);\r\n");
      out.write(" \t      \t$('#option_b2').attr(\"disabled\", false);\r\n");
      out.write("    \t\tprintData(dataMap.smplList, $('#smpl-list-table-tbody'), $('#smpl-list-template'), '.each-smpl-element');\r\n");
      out.write("      \t\tprintPagination(dataMap.pageMaker, $('#inptnt-list-pagination-ul'), $('#inptnt-pagination-template'), '.each-inptnt-pagination-element');\r\n");
      out.write("      \t\tshowDetail(dataMap.smplList[0].smplNo);\r\n");
      out.write("    \t}\r\n");
      out.write("    },\r\n");
      out.write("    error : function(error){\r\n");
      out.write("      alert('error' + error.status);\r\n");
      out.write("    }\r\n");
      out.write("  })\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write("//jsonArray는 ResponseEntity에서 넣어준 List가 들어가는 자리\r\n");
      out.write("//target은 handlebars로 생성한 마크업을 append할 대상으로 jquery객체이며 리스트에서 쓸 경우 보통 tbody에 id를 줘서 target으로 잡는다.\r\n");
      out.write("//templateObject는 handlebars를 이용하여 만든 템플릿으로 jquery객체이다.\r\n");
      out.write("//removeClass는 append하기전에 기존에 있던 리스트<여기서는 handlebars로 붙인 요소 목록>를 지우기 위해서 '.(클래스이름)'을 넣는다.\r\n");
      out.write("//이를 위하여 templateObject에서 handlebars로 붙인 요소 목록를 지칭할 class를 주어야 한다. 여기서는 .each-inptnt-element이며,\r\n");
      out.write("//tr태그에 붙어있다.\r\n");
      out.write("function printData(jsonArray, target, templateObject, removeClass){\r\n");
      out.write("\r\n");
      out.write("\t// templateObject를 json data를 받으면 마크업을 return하는 function template로 반환한다.\r\n");
      out.write("\tvar template = Handlebars.compile(templateObject.html());\r\n");
      out.write("\t\r\n");
      out.write("\t// 함수 template에 파라미터 jsonArray를 넣어서 실행하여 html을 생성한다.\r\n");
      out.write("\tvar html = template(jsonArray);\r\n");
      out.write("\t\r\n");
      out.write("\t// 해당 html요소를 append하기 전에 기존에 있던 내용을 지운다. (안그러면 리스트 목록이 10개씩만 보이는 게 아니라 10개, 20개, 30개 등 페이지 클릭할 때마다 10개씩 추가되므로)\r\n");
      out.write("\t$(removeClass).remove();\r\n");
      out.write("\t\r\n");
      out.write("\t// html요소를 append한다.\r\n");
      out.write("\ttarget.append(html);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function printPagination(pageMaker, target, templateObject, removeClass){\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tvar pageNum = new Array(pageMaker.endPage-pageMaker.startPage+1);\r\n");
      out.write("\t\r\n");
      out.write("\tfor(var i=0;i<pageMaker.endPage-pageMaker.startPage+1;i++){\r\n");
      out.write("\t\tpageNum[i]=pageMaker.startPage+i;\r\n");
      out.write("\t}\t\r\n");
      out.write("\tpageMaker.pageNum=pageNum;  \r\n");
      out.write("\tpageMaker.prevPageNum=pageMaker.startPage-1;\r\n");
      out.write("\tpageMaker.nextPageNum=pageMaker.endPage+1;\r\n");
      out.write("\t\r\n");
      out.write("\tvar template=Handlebars.compile(templateObject.html());\t\r\n");
      out.write("\tvar html = template(pageMaker);\t\r\n");
      out.write("\ttarget.html(\"\").html(html);\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("var data = \"\";\r\n");
      out.write("\r\n");
      out.write("function generateQR(pstiNo, smplNo){\r\n");
      out.write("\t\r\n");
      out.write("\tconsole.log(pstiNo);\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#qrBox\").empty();\r\n");
      out.write("\t\r\n");
      out.write("\tvar qrcode = new QRCode(document.getElementById(\"qrBox\"));\r\n");
      out.write("\tvar url = 'http://192.168.143.14");
      out.print(request.getContextPath());
      out.write("/common/qrInfo?pstiNo=' + pstiNo + '&smplNo=' + smplNo;\r\n");
      out.write("\t\r\n");
      out.write("\tif(!pstiNo) url = \"\";\r\n");
      out.write("\t\r\n");
      out.write("\tqrcode.makeCode(url);\r\n");
      out.write("}\r\n");
      out.write("function decode() {\r\n");
      out.write("\t//alert(data);\r\n");
      out.write("\tvar devalue = document.getElementById('decodetext');\r\n");
      out.write("\tdevalue.value = data;\r\n");
      out.write("}\r\n");
      out.write("\tfunction checkAllBox(checkBox){\r\n");
      out.write("\t\t//alert(\"눌림\");\r\n");
      out.write("\t\tvar length = document.getElementsByName(\"checkSmple\").length;\r\n");
      out.write("\t\t//alert(\"length:\"+length);\r\n");
      out.write("\t\tif(document.getElementById('all').checked==true){\r\n");
      out.write("\t\t\tfor(var i=0; i<length; i++) document.getElementsByName(\"checkSmple\")[i].checked=true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(document.getElementById('all').checked==false){\r\n");
      out.write("\t\t\tfor(var i=0; i<length; i++) document.getElementsByName(\"checkSmple\")[i].checked=false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function showDetail(smplNo, manageNo, checkAll){\r\n");
      out.write("\t\r\n");
      out.write("\t  var trs = $('tr.each-smpl-element');\r\n");
      out.write("\t  \r\n");
      out.write("\t  trs.removeClass('on');\r\n");
      out.write("\t  \r\n");
      out.write("\t  var target = $('tr[data-smpl-no=\"'+smplNo+'\"]');\r\n");
      out.write("\t  \r\n");
      out.write("\t  target.addClass('on');\r\n");
      out.write("\t  \r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t    url : '");
      out.print(request.getContextPath() );
      out.write("/rest-pbht/smpl-detail',\r\n");
      out.write("\t    type : 'get',\r\n");
      out.write("\t    dataType : 'json',\r\n");
      out.write("\t    data : {'smplNo':smplNo},\r\n");
      out.write("\t    success : function(dataMap){\r\n");
      out.write("\t \t\tconsole.log(dataMap);\r\n");
      out.write("\t    \t$('#req_ymd').html(prettifyDate(dataMap.reqYmd));\r\n");
      out.write("\t\t\t$('#inst_nm').html(dataMap.instNm);\r\n");
      out.write("\t\t\t$('#psti_nm').html(dataMap.pstiNm);\r\n");
      out.write("\t\t\t$('#bir').html(dataMap.bir);\r\n");
      out.write("\t\t\t$('#psti_telno').html(dataMap.pstiTelno);\r\n");
      out.write("\t\t\t$('#rechkd_yn').html(dataMap.rechkdYn);\r\n");
      out.write("\t\t\t$('#psti_adres').html(dataMap.pstiAdres);\r\n");
      out.write("\t\t\t$('#req_inst_nm').html(dataMap.reqInstNm);\r\n");
      out.write("\t\t\t$('#inst_telno').html(dataMap.instTelno);\r\n");
      out.write("\t \t\t$('#inst_adres').html(dataMap.instAdres); \r\n");
      out.write("\t \t\t// 확정버튼 세팅\r\n");
      out.write("\t \t\t$('#data-smpl-no').val(dataMap.smplNo);\r\n");
      out.write("\t \t\t$('#data-manage-no').val(dataMap.manageNo);\r\n");
      out.write("\t \t\t\r\n");
      out.write("\t \t\tconsole.log($('#pstiNoInput')[0]);\r\n");
      out.write("\t \t\t\r\n");
      out.write("\t \t\t$('#pstiNoInput').val(dataMap.pstiNo);\r\n");
      out.write("\t \t\t\r\n");
      out.write("\t \t\t\r\n");
      out.write("\t \t\tgenerateQR(dataMap.pstiNo, smplNo)\r\n");
      out.write("\t \t\t\r\n");
      out.write("\t    },\r\n");
      out.write("\t    error : function(error){\r\n");
      out.write("\t      alert('error' + error.status);\r\n");
      out.write("\t    }\r\n");
      out.write("\t  })\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function prettifyDate(timeValue){\r\n");
      out.write("\tif(timeValue){\r\n");
      out.write("\t\tvar dateObj = new Date(timeValue);\r\n");
      out.write("\t\tvar year = dateObj.getFullYear();\r\n");
      out.write("\t\tvar month = dateObj.getMonth() + 1;\r\n");
      out.write("\t\tmonth += '';\r\n");
      out.write("\t\tif(month.length < 2){\r\n");
      out.write("\t\t\tmonth = '0' + month;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar date = dateObj.getDate();\r\n");
      out.write("\t\tdate += '';\r\n");
      out.write("\t\tif(date.length < 2){\r\n");
      out.write("\t\t\tdate = '0' + date;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn year + \"-\" + month + \"-\" + date;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn \"없음\";\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("function searchfalse(){\r\n");
      out.write("\t$('#req_ymd').html(\"\");\r\n");
      out.write("\t$('#inst_nm').html(\"\");\r\n");
      out.write("\t$('#psti_nm').html(\"\");\r\n");
      out.write("\t$('#bir').html(\"\");\r\n");
      out.write("\t$('#psti_telno').html(\"\");\r\n");
      out.write("\t$('#rechkd_yn').html(\"\");\r\n");
      out.write("\t$('#psti_adres').html(\"\");\r\n");
      out.write("\t$('#req_inst_nm').html(\"\");\r\n");
      out.write("\t$('#inst_telno').html(\"\");\r\n");
      out.write("\t$('#inst_adres').html(\"\"); \r\n");
      out.write("\t// 확정버튼 세팅\r\n");
      out.write("\t$('#data-smpl-no').val(\"\");\r\n");
      out.write("\t$('#data-manage-no').val(\"\");\r\n");
      out.write("\t\r\n");
      out.write("\t$('#pstiNoInput').val(\"\");\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#qrBox\").empty();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function psti_check_all(checkAll){\r\n");
      out.write("\t// alert(\"왔음 ?\");\r\n");
      out.write("\t// var checktest = document.querySelectorAll('input[type=\"checkbox\"]');\r\n");
      out.write("\tif($(checkAll).prop(\"checked\")){\r\n");
      out.write("        $(\"input[type=checkbox]\").prop(\"checked\",true);\r\n");
      out.write("    }else{\r\n");
      out.write("        $(\"input[type=checkbox]\").prop(\"checked\",false);\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function cancleAll(check){\r\n");
      out.write("\t if(!$(check).prop(\"checked\")) $(\"input[name=psti_check_all]\").prop(\"checked\",false);\r\n");
      out.write("\t //psti_req_check\r\n");
      out.write("\t \r\n");
      out.write("\t if(($(\"input[type=checkbox]\").length-1) == $(\"input[name=psti_req_check]:checked\").length) $(\"input[name=psti_check_all]\").prop(\"checked\",true);\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<section class=\"content\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\" style=\"height: 70px; margin: 1px;\">\r\n");
      out.write("\t\t<div class=\"col-lg-6 pl-0\" style=\"margin-top: 17px; margin-bottom: 12px;\">\r\n");
      out.write("\t\t\t<div class=\"card\" style=\"margin: 1px; padding-bottom: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t<!-- sort num -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-header d-flex p-0\">\r\n");
      out.write("\t\t\t\t\t\t<select name=\"checkResult\" style=\"width: 55px; height: 30px;margin-top: 8px;margin-left: 17px;margin-right: 4px;\">\r\n");
      out.write("                      \t<option value=\"\" selected=\"selected\">미정</option>\r\n");
      out.write("                      \t<option value=\"A102\">양성</option>\r\n");
      out.write("                      \t<option value=\"A103\">음성</option>\r\n");
      out.write("                      </select>\r\n");
      out.write("\t\t\t\t\t\t<button onclick=\"smplsConfirmed_go();\" class=\"btn btn-success\" name=\"options\" id=\"option_b1\" style=\"margin-top: 8px;height: 30px;width: 67px;background: #1a4f72; border: #1a4f72;\">확정</button>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"nav nav-pills ml-auto p-2\" role=\"tablist\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group float-right\" style=\"max-width: 600px; width:300px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- search bar -->\r\n");
      out.write("                    \t\r\n");
      out.write("\t\t\t\t\t\t<select class=\"form-control \" name=\"searchType\" id=\"searchType\" >\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.searchType eq '' ? 'selected':''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">검색구분</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"smpl\"\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.searchType eq 'smpl' ? 'selected':''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">시료번호</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"inst\"\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.searchType eq 'inst' ? 'selected':''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">요청기관</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- keyword -->\r\n");
      out.write("\t\t\t\t\t\t<input id=\"keywordId\" class=\"form-control\" type=\"text\" name=\"keyword\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.keyword }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 18%; display: inline-block;\" />\r\n");
      out.write("\t\t\t\t\t\t<span class=\"input-group-append\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-primary\" type=\"button\" id=\"searchBtn\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"background: #1a4f72; color: #ffffff; border-color: #1a4f72; display: inline-block; margin-bottom: 4px; margin-left: -7px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-card-widget=\"search\" onclick=\"list_go('");
      out.print(request.getContextPath() );
      out.write("/rest-pbht/smpl-list', 1, true);\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa fa-fw fa-search\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- end : search bar -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body pb-0\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ddoing\" style=\"height: 650px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"table table-hover text-nowrap\"style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t                      <th tabindex=\"0\" aria-controls=\"example2\" rowspan=\"1\" colspan=\"1\" aria-label=\"Browser: activate to sort column ascending\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"form-group m-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  <div class=\"form-check p-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  <input type=\"checkbox\" class=\"form-check-input-all\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t name=\"psti_check_all\" onclick=\"psti_check_all(this);\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t  </th>\r\n");
      out.write("\t\t\t                      <th>시료번호</th>\r\n");
      out.write("\t\t\t                      <th>요청기관</th>\r\n");
      out.write("\t\t\t                      <th>요청일</th>\r\n");
      out.write("\t\t\t                      <th>검사여부</th>\r\n");
      out.write("\t\t\t                    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody id=\"smpl-list-table-tbody\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr class=\"each-smpl-element\" >\r\n");
      out.write("\t\t\t\t                      <td colspan=\"5\" id=\"noSemlpeData\">데이터 로딩중 입니다.</td>\r\n");
      out.write("\t\t\t\t                    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t  <div class=\"card-footer clearfix\" style=\"background-color: white;\">\r\n");
      out.write("\t\t\t    <ul class=\"pagination justify-content-center m-0\" id=\"inptnt-list-pagination-ul\">\r\n");
      out.write("\t\t\t    </ul>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t<form id=\"jobForm\">\r\n");
      out.write("\t\t\t  <input type='hidden' name=\"page\" value=\"\" />\r\n");
      out.write("\t\t\t  <input type='hidden' name=\"perPageNum\" value=\"\"/>\r\n");
      out.write("\t\t\t  <input type='hidden' name=\"searchType\" value=\"\" />\r\n");
      out.write("\t\t\t  <input type='hidden' name=\"keyword\" value=\"\" />\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-lg-6 pr-0\" style=\"margin-top: 17px;\">\r\n");
      out.write("\t\t <div class=\"card\" style=\"margin-bottom: 7px;\">\r\n");
      out.write("\t\t\t<form name=\"psti-regist-form\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/insp/psti-regist\" method=\"post\">\r\n");
      out.write("\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t  <div class=\"row\" style=\"justify-content: center;\">\r\n");
      out.write("\t\t\t\t<div id=\"qrBox\" class=\"brand-link mt-2 pb-3 mb-3 d-flex\"\r\n");
      out.write("\t\t\t\t\tstyle=\"background-size: cover; background-position: center; background-repeat: no-repeat; height: 135px; text-align: center;\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"input-group mb-3\" style=\"justify-content: center;\">\r\n");
      out.write("\t\t\t\t<div class=\"login-box-msg\"\r\n");
      out.write("\t\t\t\t\tstyle=\"display: inline-block; width: 50px;\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-qrcode fa-2x\"></i>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"pstiNoInput\" id=\"pstiNoInput\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"\" readonly style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("                <table class=\"table table-bordered\">\r\n");
      out.write("                  <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <th colspan=\"4\">검사결과 정보</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                  </thead>\r\n");
      out.write("                  <tbody>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <th class=\"col-md-2\"><strong>요청일자</strong></th>\r\n");
      out.write("                      <td class=\"col-md-4\" id=\"req_ymd\" ></td>\r\n");
      out.write("                      <th class=\"col-md-2\"><strong>확정일자</strong></th>\r\n");
      out.write("                      <td class=\"col-md-4\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    \r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <th><strong>검사결과</strong></th>\r\n");
      out.write("                      <td>\r\n");
      out.write("\t                      <select name=\"result\">\r\n");
      out.write("\t                      \t<option value=\"\" selected=\"selected\">미정</option>\r\n");
      out.write("\t                      \t<option value=\"A102\">양성</option>\r\n");
      out.write("\t                      \t<option value=\"A103\">음성</option>\r\n");
      out.write("\t                      </select>\r\n");
      out.write("                      </td>\r\n");
      out.write("                      <th><strong>검사기관</strong></th>\r\n");
      out.write("                      <td id=\"inst_nm\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                  </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"margin: 0 auto;\" class=\"col-2\">\r\n");
      out.write("\t\t\t\t<button  \r\n");
      out.write("\t\t\t\ttype=\"button\" id=\"option_b2\" class=\"btn btn-block btn-default\" onclick=\"smplConfirmed_go();\" style=\"background-color: #1a4f72; border: #1a4f72;\">\r\n");
      out.write("\t\t\t\t<span style=\"color: white;\">확정</span></button>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<form id=\"smplConfirmed\" action=\"");
      out.print(request.getContextPath() );
      out.write("/pbhlth/smpl-confirmed\" method=\"post\">\r\n");
      out.write("\t\t\t\t<input id=\"data-smpl-no\" type=\"hidden\" name=\"smplNo\" value=\"\"/>\r\n");
      out.write("\t\t\t\t<input id=\"data-manage-no\" type=\"hidden\" name=\"manageNo\" value=\"\"/>\r\n");
      out.write("\t\t\t\t<input id=\"data-result-code\" type=\"hidden\" name=\"sttusCode\" value=\"\" />\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<form id=\"smplsConfirmed\" action=\"");
      out.print(request.getContextPath() );
      out.write("/pbhlth/smpls-confirmed\" method=\"post\">\r\n");
      out.write("\t\t\t\t<input id=\"data-smpls-no\" type=\"hidden\" name=\"smplNo\" value=\"\"/>\r\n");
      out.write("\t\t\t\t<input id=\"data-manages-no\" type=\"hidden\" name=\"manageNo\" value=\"\"/>\r\n");
      out.write("\t\t\t\t<input id=\"data-results-code\" type=\"hidden\" name=\"sttusCode\" value=\"\" />\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"card-body\">\r\n");
      out.write("                <table class=\"table table-bordered\">\r\n");
      out.write("                  <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <th colspan=\"4\">피검자정보</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                  </thead>\r\n");
      out.write("                  <tbody>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <th class=\"col-md-2\"><strong>성명</strong></th>\r\n");
      out.write("                      <td class=\"col-md-4\" style=\"border-top: 2px solid black;\" id=\"psti_nm\" ></td>\r\n");
      out.write("                      \r\n");
      out.write("                      <th class=\"col-md-2\"><strong>생년월일</strong></th>\r\n");
      out.write("                      <td class=\"col-md-4\" style=\"border-top: 2px solid black;\" id=\"bir\"></td>\r\n");
      out.write("                      \r\n");
      out.write("                    </tr>\r\n");
      out.write("                    \r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <th><strong>연락처</strong></th>\r\n");
      out.write("                      <td id=\"psti_telno\"></td>\r\n");
      out.write("                      <th><strong>재검여부</strong></th>\r\n");
      out.write("                      <td id=\"rechkd_yn\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    \r\n");
      out.write("                     <tr>\r\n");
      out.write("                      <th><strong>주소</strong></th>\r\n");
      out.write("                      <td colspan=\"3\" id=\"psti_adres\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                  </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"card-body\" style=\"margin-bottom: 20px;\">\r\n");
      out.write("                <table class=\"table table-bordered\">\r\n");
      out.write("                  <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <th colspan=\"6\">검사 요청기관</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                  </thead>\r\n");
      out.write("                  <tbody>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <th class=\"col-md-2\"><strong>요청기관</strong></th>\r\n");
      out.write("                      <td class=\"col-md-4\" id=\"req_inst_nm\" ></td>\r\n");
      out.write("                      <th class=\"col-md-2\"><strong>연락처</strong></th>\r\n");
      out.write("                      <td class=\"col-md-4\" id=\"inst_telno\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    \r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <th><strong>주소</strong></th>\r\n");
      out.write("                      <td colspan=\"5\" id=\"inst_adres\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                     \r\n");
      out.write("                  </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("                  <div style=\"margin-bottom: 7px;\"></div>\r\n");
      out.write("                \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</section>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function smplConfirmed_go(){\r\n");
      out.write("\t\r\n");
      out.write("\tif(!$('select[name=\"result\"]').val()){\r\n");
      out.write("\t\talert(\"검사결과를 선택해 주세요.\")\t  \r\n");
      out.write("\t\treturn; \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar check = confirm(\"결과를 등록하시겠습니까?\");\r\n");
      out.write("\t\r\n");
      out.write("\tif(check){\r\n");
      out.write("\t\tvar result = $('select[name=\"result\"]').val();\r\n");
      out.write("\t\t$('#data-result-code').val(result);\r\n");
      out.write("\t\t$('#smplConfirmed').submit();\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function smplsConfirmed_go(){\r\n");
      out.write("\tvar smplNo = \"\";  \r\n");
      out.write("\tvar manageNo = \"\";\r\n");
      out.write("\t\r\n");
      out.write("\tif(!$('select[name=\"checkResult\"]').val()){\r\n");
      out.write("\t\talert(\"검사결과를 선택해 주세요.\")\t  \r\n");
      out.write("\t\treturn; \r\n");
      out.write("\t}\r\n");
      out.write("\tif($('input[class=\"form-check-input\"]:checked').length == 0){\r\n");
      out.write("\t\talert(\"시료를 선택해 주세요.\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar check = confirm(\"결과를 등록하시겠습니까?\");\r\n");
      out.write("\t\r\n");
      out.write("\tif(check){\r\n");
      out.write("\t\t$('input[class=\"form-check-input\"]:checked').each(function(){\r\n");
      out.write("\t\t    smplNo += $(this).val()+ \",\";\r\n");
      out.write("\t\t    manageNo += $(this).attr('data-manage-no') + \",\";\r\n");
      out.write("\t\t});\r\n");
      out.write("\t  \tvar result = $('select[name=\"checkResult\"]').val();\r\n");
      out.write("\t    $('#data-smpls-no').val(smplNo);\r\n");
      out.write("\t    $('#data-manages-no').val(manageNo);\r\n");
      out.write("\t    $('#data-results-code').val(result);\r\n");
      out.write("\t    $('#smplsConfirmed').submit(); \r\n");
      out.write("\t}else{\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
